source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

target 'DailyTodoNative' do
  use_frameworks!

  pod 'Lynx', '3.8.0', :subspecs => [
    'Framework',
  ]

  pod 'PrimJS', '3.8.0', :subspecs => ['quickjs', 'napi']

  pod 'LynxService', '3.8.0', :subspecs => [
    'Image',
    'Log',
    'Http',
  ]

  pod 'SDWebImage', '5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'
end
